### ISSUE TITLE
No services listed: prodigy.el:1383:1:Warning: the following functions are not known to be defined: -clone, -first-item,

### ISSUE THREAD

**Issue by Michieljoris** [rejeep/prodigy.el#58] opened 2014-08-28 04:20 UTC
After defining a service and M-x prodigy, nothing shows up. The following warning is given when M-x evalling the buffer:
prodigy.el:1383:1:Warning: the following functions are not known to be defined: -clone, -first-item,

**Comment by Fuco1** [comment] 2018-03-09 16:46
This was caused by not having dash.el library in the load path.  Closing as this is 4 years old.  If still a problem hit us up.

**Closed by Fuco1** 2018-03-09 16:46 UTC
